import * as BibleVerse from "@/Database/bible.content";

const listBooks = [
  {
    titre: "Genèse",
    abr: [
      "gen",
      "Gen",
      "gns",
      "GNS",
      "GEN",
      "Gns",
      "Gn",
      "gn",
      "Geneses",
      "GENESES",
      "GENES",
      "Genes",
      "genes",
      "genese",
    ],
    index: "A1",
    nbr_chap: 50,
    livre: 1,
  },
  {
    titre: "Exode",
    abr: [
      "Ex",
      "Exo",
      "exo",
      "ex",
      "EXO",
      "EX",
      "EXODE",
      "Exode",
      "exode",
      "exodus",
      "EXODUS",
      "Exodus",
    ],
    index: "A2",
    nbr_chap: 40,
    livre: 2,
  },
  {
    titre: "Lévitique",
    abr: ["LV", "Lv", "lv", "LEV", "Lev", "lev"],
    index: "A3",
    nbr_chap: 27,
    livre: 3,
  },
  {
    titre: "Nombres",
    abr: ["NOMB", "Nomb", "nomb", "NBR", "Nbr", "nbr"],
    index: "A4",
    nbr_chap: 36,
    livre: 4,
  },
  {
    titre: "Deutéronome",
    abr: ["DEUT", "Deut", "deut"],
    index: "A5",
    nbr_chap: 34,
    livre: 5,
  },
  {
    titre: "Josué",
    abr: ["JOS", "Jos", "jos"],
    index: "A6",
    nbr_chap: 24,
    livre: 6,
  },
  {
    titre: "Juges",
    abr: ["JUG", "jug", "jug"],
    index: "A7",
    nbr_chap: 21,
    livre: 7,
  },
  {
    titre: "Ruth",
    abr: ["RUT", "Rut", "rut", "ruth", "Ruth", "Rt", "RT", "rt"],
    index: "A8",
    nbr_chap: 4,
    livre: 8,
  },
  {
    titre: "1 Samuel",
    abr: [
      "1SAM",
      "1Sam",
      "1sam",
      "1 SAM",
      "1 Sam",
      "1 sam",
      "1SM",
      "1Sm",
      "1sm",
      "1 SM",
      "1 Sm",
      "1 sm",
      "1S",
      "1s",
    ],
    index: "A9",
    nbr_chap: 31,
    livre: 9,
  },
  {
    titre: "2 Samuel",
    abr: [
      "2SAM",
      "2Sam",
      "2sam",
      "2 SAM",
      "2 Sam",
      "2 sam",
      "2SM",
      "2Sm",
      "2sm",
      "2 SM",
      "2 Sm",
      "2 sm",
      "2S",
      "2s",
    ],
    index: "A10",
    nbr_chap: 24,
    livre: 10,
  },
  {
    titre: "1 Rois",
    abr: [
      "1RS",
      "1Rs",
      "1rs",
      "1 Rs",
      "1 RS",
      "1 rs",
      "1R",
      "1r",
      "1 R",
      "1 r",
    ],
    index: "A11",
    nbr_chap: 22,
    livre: 11,
  },
  {
    titre: "2 Rois",
    abr: [
      "2RS",
      "2Rs",
      "2rs",
      "2 Rs",
      "2 RS",
      "2 rs",
      "2R",
      "2r",
      "2 R",
      "2 r",
    ],
    index: "A12",
    nbr_chap: 25,
    livre: 12,
  },
  {
    titre: "1 Chroniques",
    abr: ["1CH", "1Ch", "1ch", "1 CH", "1 Ch", "1 ch"],
    index: "A13",
    nbr_chap: 29,
    livre: 13,
  },
  {
    titre: "2 Chroniques",
    abr: ["2CH", "2Ch", "2ch", "2 CH", "2 Ch", "2 ch"],
    index: "A14",
    nbr_chap: 36,
    livre: 14,
  },
  {
    titre: "Esdras",
    abr: ["ESD", "Esd", "esd"],
    index: "A15",
    nbr_chap: 10,
    livre: 15,
  },
  {
    titre: "Néhémie",
    abr: ["NEH", "Neh", "neh", "NH", "Nh", "nh"],
    index: "A16",
    nbr_chap: 13,
    livre: 16,
  },
  {
    titre: "Esther",
    abr: ["EST", "Est", "est", "Esth", "esth", "ESTH"],
    index: "A17",
    nbr_chap: 10,
    livre: 17,
  },
  {
    titre: "Job",
    abr: ["JOB", "job", "jb", "Jb", "JB"],
    index: "A18",
    nbr_chap: 42,
    livre: 18,
  },
  {
    titre: "Psaumes",
    abr: ["PS", "Ps", "ps"],
    index: "A19",
    nbr_chap: 150,
    livre: 19,
  },
  {
    titre: "Proverbes",
    abr: [
      "PR",
      "Pr",
      "pr",
      "Pro",
      "PRO",
      "pro",
      "PROV",
      "Prov",
      "prov",
      "PRo",
      "PRov",
      "PROv",
    ],
    index: "A20",
    nbr_chap: 31,
    livre: 20,
  },
  {
    titre: "Ecclésiaste",
    abr: ["EC", "Ec", "ec"],
    index: "A21",
    nbr_chap: 12,
    livre: 21,
  },
  {
    titre: "Cantique",
    abr: ["CAN", "Can", "can", "Cant", "CANT", "cant"],
    index: "A22",
    nbr_chap: 8,
    livre: 22,
  },
  {
    titre: "Esaïe",
    abr: [
      "ES",
      "Es",
      "es",
      "Essaie",
      "ESSAIE",
      "essaie",
      "Ess",
      "ESS",
      "ess",
      "Esaie",
      "esaie",
      "ESAIE",
      "Esa",
      "ESA",
      "esa",
      "Esai",
      "esai",
      "ESAI",
    ],
    index: "A23",
    nbr_chap: 66,
    livre: 23,
  },
  {
    titre: "Jérémie",
    abr: ["JER", "Jer", "jer", "JR", "Jr", "jr"],
    index: "A24",
    nbr_chap: 52,
    livre: 24,
  },
  {
    titre: "Lamentations",
    abr: ["LAM", "Lam", "lam"],
    index: "A25",
    nbr_chap: 5,
    livre: 25,
  },
  {
    titre: "Ezéchiel",
    abr: ["EZ", "Ez", "ez", "EZE", "Eze", "eze"],
    index: "A26",
    nbr_chap: 48,
    livre: 26,
  },
  {
    titre: "Daniel",
    abr: [
      "DAN",
      "Dan",
      "dan",
      "Daniel",
      "daniel",
      "DANIEL",
      "dani",
      "Dani",
      "DANI",
    ],
    index: "A27",
    nbr_chap: 12,
    livre: 27,
  },
  {
    titre: "Osée",
    abr: ["OS", "Os", "os", "OSE", "Ose", "ose"],
    index: "A28",
    nbr_chap: 14,
    livre: 28,
  },
  {
    titre: "Joël",
    abr: ["joel", "JOEL", "Joel"],
    index: "A29",
    nbr_chap: 3,
    livre: 29,
  },
  {
    titre: "Amos",
    abr: ["AMOS", "amos", "AM", "Am", "am"],
    index: "A30",
    nbr_chap: 9,
    livre: 30,
  },
  {
    titre: "Abdias",
    abr: ["ABD", "Abd", "abd"],
    index: "A31",
    nbr_chap: 1,
    livre: 31,
  },
  {
    titre: "Jonas",
    abr: ["JONAS", "jonas", "Jon", "JON", "jon"],
    index: "A32",
    nbr_chap: 4,
    livre: 32,
  },
  {
    titre: "Michée",
    abr: ["MIC", "Mic", "mic", "MICH", "Mich", "mich"],
    index: "A33",
    nbr_chap: 7,
    livre: 33,
  },
  {
    titre: "Nahum",
    abr: ["NAH", "Nah", "nah"],
    index: "A34",
    nbr_chap: 3,
    livre: 34,
  },
  {
    titre: "Habacuc",
    abr: ["HAB", "Hab", "hab"],
    index: "A35",
    nbr_chap: 3,
    livre: 35,
  },
  {
    titre: "Sophonie",
    abr: ["SOPH", "Soph", "soph"],
    index: "A36",
    nbr_chap: 3,
    livre: 36,
  },
  {
    titre: "Aggée",
    abr: [
      "AGG",
      "Agg",
      "agg",
      "Aggee",
      "AGGEE",
      "Agge",
      "agge",
      "Aggée",
      "aggée",
      "AGGÉE",
    ],
    index: "A37",
    nbr_chap: 2,
    livre: 37,
  },
  {
    titre: "Zacharie",
    abr: [
      "ZACH",
      "Zach",
      "zach",
      "ZAC",
      "Zac",
      "zac",
      "ZACHARIE",
      "Zacharie",
      "zacharie",
    ],
    index: "A38",
    nbr_chap: 14,
    livre: 38,
  },
  {
    titre: "Malachie",
    abr: ["MAL", "Mal", "mal", "malachie", "Malachie", "MALACHIE"],
    index: "A39",
    nbr_chap: 4,
    livre: 39,
  },
  {
    titre: "Matthieu",
    abr: [
      "MAT",
      "Mat",
      "mat",
      "MTT",
      "Mtt",
      "mtt",
      "matthieu",
      "Matthieu",
      "MATTHIEU",
      "Mathieu",
      "mathieu",
      "MATHIEU",
      "MATT",
      "Matt",
      "matt",
      "Math",
      "math",
      "MATH",
      "matth",
      "Matth",
      "MATTH",
    ],
    index: "N1",
    nbr_chap: 28,
    livre: 40,
  },
  {
    titre: "Marc",
    abr: ["MARC", "marc", "Marc", "mrc", "MRC", "Mrc"],
    index: "N2",
    nbr_chap: 16,
    livre: 41,
  },
  {
    titre: "Luc",
    abr: ["LUC", "luc", "Luc", "lc", "LC", "lc"],
    index: "N3",
    nbr_chap: 24,
    livre: 42,
  },
  {
    titre: "Jean",
    abr: ["JN", "Jn", "jn", "Jean", "jean", "JEAN"],
    index: "N4",
    nbr_chap: 21,
    livre: 43,
  },
  {
    titre: "Actes",
    abr: ["ACT", "Act", "act", "Actes", "ACTES", "actes"],
    index: "N5",
    nbr_chap: 28,
    livre: 44,
  },
  {
    titre: "Romains",
    abr: [
      "ROM",
      "Rom",
      "rom",
      "romains",
      "Romains",
      "ROMAINS",
      "Rm",
      "rm",
      "RM",
    ],
    index: "N6",
    nbr_chap: 16,
    livre: 45,
  },
  {
    titre: "1 Corinthiens",
    abr: [
      "1COR",
      "1Cor",
      "1cor",
      "1COR",
      "1Cor",
      "1cor",
      "1corinthiens",
      "1Corinthiens",
      "1CORINTHIENS",
    ],
    index: "N7",
    nbr_chap: 16,
    livre: 46,
  },
  {
    titre: "2 Corinthiens",
    abr: ["2COR", "2Cor", "2cor", "2 COR", "2 Cor", "2 cor"],
    index: "N8",
    nbr_chap: 13,
    livre: 47,
  },
  {
    titre: "Galates",
    abr: ["GAL", "Gal", "gal"],
    index: "N9",
    nbr_chap: 6,
    livre: 48,
  },
  {
    titre: "Ephésiens",
    abr: ["EPH", "Eph", "eph"],
    index: "N10",
    nbr_chap: 6,
    livre: 49,
  },
  {
    titre: "Philippiens",
    abr: ["PHIL", "Phil", "phil"],
    index: "N11",
    nbr_chap: 4,
    livre: 50,
  },
  {
    titre: "Colossiens",
    abr: ["COL", "Col", "col"],
    index: "N12",
    nbr_chap: 4,
    livre: 51,
  },
  {
    titre: "1 Thessalonicien",
    abr: ["1TH", "1Th", "1th", "1 TH", "1 Th", "1 th"],
    index: "N12",
    nbr_chap: 5,
    livre: 52,
  },
  {
    titre: "2 Thessalonicien",
    abr: ["2TH", "2Th", "2th", "2 TH", "2 Th", "2 th"],
    index: "N13",
    nbr_chap: 3,
    livre: 53,
  },
  {
    titre: "1 Timothée",
    abr: ["1TIM", "1Tim", "1tim", "1 TIM", "1 Tim", "1 tim"],
    index: "N14",
    nbr_chap: 6,
    livre: 54,
  },
  {
    titre: "2 Timothée",
    abr: ["2TIM", "2Tim", "2tim", "2 TIM", "2 Tim", "2 tim"],
    index: "N15",
    nbr_chap: 4,
    livre: 55,
  },
  {
    titre: "Tite",
    abr: ["TIT", "tit"],
    index: "N16",
    nbr_chap: 3,
    livre: 56,
  },
  {
    titre: "Philémon",
    abr: ["PHIL", "Phil", "phil"],
    index: "N17",
    nbr_chap: 1,
    livre: 57,
  },
  {
    titre: "Hébreux",
    abr: ["HEB", "Heb", "heb"],
    index: "N18",
    nbr_chap: 13,
    livre: 58,
  },
  {
    titre: "Jacques",
    abr: ["JACQ", "Jacq", "jacq"],
    index: "N19",
    nbr_chap: 5,
    livre: 59,
  },
  {
    titre: "1 Pierre",
    abr: ["1 P", "1 p", "1P", "1p"],
    index: "N20",
    nbr_chap: 5,
    livre: 60,
  },
  {
    titre: "2 Pierre",
    abr: ["2 P", "2 p", "2P", "2p"],
    index: "N21",
    nbr_chap: 3,
    livre: 61,
  },
  {
    titre: "1 Jean",
    abr: ["1Jn", "1JN", "1jn", "1 JN", "1 Jn", "1 jn"],
    index: "N22",
    nbr_chap: 5,
    livre: 62,
  },
  {
    titre: "2 Jean",
    abr: ["2Jn", "2JN", "2jn", "2 JN", "2 Jn", "2 jn"],
    index: "N23",
    nbr_chap: 1,
    livre: 63,
  },
  {
    titre: "3 Jean",
    abr: ["3Jn", "3JN", "3jn", "3 JN", "3 Jn", "3 jn"],
    index: "N24",
    nbr_chap: 1,
    livre: 64,
  },
  {
    titre: "Jude",
    abr: ["JUDE", "jude", "Jud", "jud", "JUD", "Jude", "Jd", "jd", "JD"],
    index: "N25",
    nbr_chap: 1,
    livre: 65,
  },
  {
    titre: "Révélation",
    abr: ["APO", "Apo", "apo"],
    index: "N26",
    nbr_chap: 22,
    livre: 66,
  },
];

/**
 * Recherche des versets dans la base de données
 */
export const filterBible = async (
  data: [
    book_id: string,
    book_name: string,
    chapter: string,
    vers1?: string,
    vers2?: string
  ]
) => {
  const [book_id, book_name, chapter, vers1, vers2] = data;

  const findbook = listBooks.find((el) => el.abr.includes(book_name));
  const ref = {
    book_id: book_id,
    book: findbook?.livre,
    chapter: parseInt(chapter),
  };
  const find = await BibleVerse.find(ref);
  if (vers1 && vers2) {
    const verseStart = parseInt(vers1);
    const verseEnd = parseInt(vers2);
    const arr = [];
    const titre = find[0].book_name;

    for (let i = verseStart; i <= verseEnd; i++) {
      const v = find.filter((el) => el.verse === i)[0].text;
      const obj = {
        n: i < 10 ? `0${i}` : i,
        text: v,
      };
      arr.push(obj);
    }

    const ref_complet = {
      ref_bible: `${titre} ${chapter}: ${vers1}-${vers2}`,
      content: JSON.stringify(arr),
    };

    return ref_complet;
  }
  if (vers1 && !vers2) {
    const verseStart = parseInt(vers1);
    const titre = find[0].book_name;
    const v = find.filter((el) => el.verse === verseStart)[0].text;

    const ref_complet = {
      ref_bible: `${titre} ${chapter}: ${vers1}`,
      content: JSON.stringify([{ n: verseStart, text: v }]),
    };
    return ref_complet;
  }
  if (!vers1 && !vers2) {
    const arr = [];
    const titre = find[0].book_name;

    for (let i = 0; i < find.length; i++) {
      const v = find.filter((el) => el.verse === i)[0].text;
      const obj = {
        n: find[i]?.verse < 10 ? `0${find[i].verse}` : find[i]?.verse,
        text: v,
      };
      arr.push(obj);
    }

    const ref_complet = {
      ref_bible: `${titre} ${chapter}`,
      content: JSON.stringify(arr),
    };

    return ref_complet;
  }
};
